### ISSUE TITLE
cupy.cuda.memory.OutOfMemoryError in forward

### ISSUE THREAD

**Issue by mfshiu** [oreilly-japan/deep-learning-from-scratch-2#16]
When I run the train_better_rnnlm.py in GPU, I got the OutOfMemoryError in forward.
But I am sure that total memory is enough. 

File "../common/time_layers.py", line 273, in forward
    out = np.dot(rx, W) + b

$ python train_better_rnnlm.py 
------------------------------------------------------------
                       GPU Mode (cupy)
------------------------------------------------------------

Traceback (most recent call last):
  File "train_better_rnnlm.py", line 47, in <module>
    time_size=time_size, max_grad=max_grad)
  File "../common/trainer.py", line 110, in fit
    loss = model.forward(batch_x, batch_t)
  File "/home/eric/work/nlp/storygen2/model/better_rnnlm.py", line 59, in forward
    score = self.predict(xs, train_flg)
  File "/home/eric/work/nlp/storygen2/model/better_rnnlm.py", line 55, in predict
    xs = layer.forward(xs)
  File "../common/time_layers.py", line 273, in forward
    out = np.dot(rx, W) + b
  File "cupy/core/core.pyx", line 928, in cupy.core.core.ndarray.__add__
  File "cupy/core/_kernel.pyx", line 836, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 340, in cupy.core._kernel._get_out_args
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 518, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1106, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 934, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 949, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 697, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 242054656 bytes (total 10076441088 bytes)

nvidia-smi
Tue Oct 13 20:48:29 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   52C    P8    15W / 280W |   1086MiB / 11178MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   39C    P8    15W / 250W |     12MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1326      G   /usr/lib/xorg/Xorg                206MiB |
|    0   N/A  N/A      2496      G   /usr/bin/gnome-shell              127MiB |
|    0   N/A  N/A     15301      G   ...AAAAAAAAA= --shared-files      145MiB |
|    0   N/A  N/A     21979      G   ...AAAAAAAAA= --shared-files       24MiB |
|    0   N/A  N/A     23646      G   ...AAAAAAAAA= --shared-files      532MiB |
|    0   N/A  N/A     28743      G   /usr/lib/xorg/Xorg                 28MiB |
|    0   N/A  N/A     28842      G   /usr/bin/gnome-shell               15MiB |
|    1   N/A  N/A      1326      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A     28743      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

**Comment by mfshiu** [comment]
I got the solution, it have to use Unified Memory to save GPU memory.

```
pool = np.cuda.MemoryPool(np.cuda.malloc_managed)
np.cuda.set_allocator(pool.malloc)
```

common/np.py should be modified like this.
```
# coding: utf-8
from common.config import GPU


if GPU:
    import cupy as np
    pool = np.cuda.MemoryPool(np.cuda.malloc_managed)
    np.cuda.set_allocator(pool.malloc)
    # np.cuda.set_allocator(np.cuda.MemoryPool().malloc)

    print('\033[92m' + '-' * 60 + '\033[0m')
    print(' ' * 23 + '\033[92mGPU Mode (cupy)\033[0m')
    print('\033[92m' + '-' * 60 + '\033[0m\n')
else:
    import numpy as np
```

**Comment by mfshiu** [comment]
I encountered this problem because the corpus I used was larger than the book example.
