### ISSUE TITLE
ch04/train.py GPU使用時エラー

### ISSUE THREAD

**Issue by kakui999** [oreilly-japan/deep-learning-from-scratch-2#4]
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    trainer.fit(contexts, target, max_epoch, batch_size)
  File "..\common\trainer.py", line 39, in fit
    loss = model.forward(batch_x, batch_t)
  File "C:\Users\kakui\Desktop\deep-learning-from-scratch-2-master\ch04\cbow.py", line 37, in forward
    h += layer.forward(contexts[:, i])
  File "..\common\layers.py", line 160, in forward
    out = W[idx]
ValueError: object __array__ method not producing an array

**Comment by kakui999** [comment]
GPU上で正常に動作しました。
ありがとうございます。
